language: ruby

rvm: 2.1

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install: bundle install

script:
  - jekyll build
  - htmlproof ./_site --allow-hash-href --only-4xx
